alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: pos-fiap-phase-2
    match:
      path:
        prefix: /
name: pos-fiap-phase2-app
region: nyc
services:
- envs:
  - key: ConnectionStrings__Default
    scope: RUN_AND_BUILD_TIME
    value: Host=ep-frosty-star-a5yudl6r.us-east-2.aws.neon.tech;Port=5432;Database=phase-one;Username=phase-one_owner;Password=ZwLjAxC0RnS5
  http_port: 8080
  image:
    deploy_on_push:
      enabled: true
    registry_type: DOCR
    repository: pos-fiap-phase2
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: pos-fiap-phase-2
